BitirmeMovieStore/BitirmeMovieStore/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BitirmeMovieStore.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        //[Authorize(Roles = "admin,manager")]
        [Authorize(Roles = "admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

BitirmeMovieStore/BitirmeMovieStore/Controllers/GenreController.cs
using BitirmeMovieStore.Models;
using BitirmeMovieStore.Repositories.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BitirmeMovieStore.Controllers
{
    [Authorize]
    public class GenreController : Controller
    {
        private readonly IGenreService _genreService;
        public GenreController(IGenreService genreService)
        {
            _genreService = genreService;
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Genre model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = _genreService.Add(model);
            if(result)
            {
                TempData["msg"] = "Added Successfully";
                return RedirectToAction(nameof(Add));
            }
            else
            {
                TempData["msg"] = "Error on Server Side";
                return View(model);
            }
        }
        public IActionResult Edit(int id)
        {
            var data = _genreService.GetById(id);
            return View(data);
        }
        [HttpPost]
        public IActionResult Update(Genre model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = _genreService.Update(model);
            if (result)
            {
                TempData["msg"] = "Added Successfully";
                return RedirectToAction(nameof(GenreList));
            }
            else
            {
                TempData["msg"] = "Error on Server Side";
                return View(model);
            }
        }
        public IActionResult GenreList() 
        {
            var data = this._genreService.List().ToList();
            return View(data);
        }
        public IActionResult Delete(int id)
        {
           
            var result = _genreService.Delete(id);
            return RedirectToAction(nameof(GenreList));
            
            
        }

    }
}

BitirmeMovieStore/BitirmeMovieStore/Controllers/MovieController.cs
using BitirmeMovieStore.Models;
using BitirmeMovieStore.Repositories.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BitirmeMovieStore.Controllers
{
    [Authorize]
    public class MovieController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IFileService _fileService;
        private readonly IGenreService _genService;


        public MovieController(IMovieService MovieService, IFileService fileService, IGenreService genService)
        {
            _movieService = MovieService;
            _fileService = fileService;
            _genService = genService;

        }
        public IActionResult Add()
        {
            var model = new Movie();
            model.GenreList = _genService.List().Select(a => new SelectListItem { Text = a.GenreName, Value = a.Id.ToString() });
            return View(model);
        }
        [HttpPost]
        public IActionResult Add(Movie model)
        {
            model.GenreList = _genService.List().Select(a => new SelectListItem { Text = a.GenreName, Value = a.Id.ToString() });
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (model.ImageFile != null)
            {
                var fileResult = this._fileService.SaveImage(model.ImageFile);
                if (fileResult.Item1 == 0)
                {
                    TempData["msg"] = "File could not saved";
                    return View(model);
                }
                var imageName = fileResult.Item2;
                model.MovieImage = imageName;
            }
            var result = _movieService.Add(model);
            if(result)
            {
                TempData["msg"] = "Added Successfully";
                return RedirectToAction(nameof(Add));
            }
            else
            {
                TempData["msg"] = "Error on Server Side";
                return View(model);
            }
        }
        public IActionResult Edit(int id)
        {
            var model = _movieService.GetById(id);
            var selectedGenres = _movieService.GetGenreByMovieId(model.Id);
            MultiSelectList multiGenreList = new MultiSelectList(_genService.List(),"Id","GenreName", selectedGenres);
            model.MultiGenreList = multiGenreList;
            return View(model);
        }
        [HttpPost]
        public IActionResult Edit(Movie model)
        {
            var selectedGenres = _movieService.GetGenreByMovieId(model.Id);
            MultiSelectList multiGenreList = new MultiSelectList(_genService.List(), "Id", "GenreName", selectedGenres);
            model.MultiGenreList = multiGenreList;
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (model.ImageFile != null)
            {
                var fileResult = this._fileService.SaveImage(model.ImageFile);
                if (fileResult.Item1 == 0)
                {
                    TempData["msg"] = "File could not saved";
                    return View(model);
                }
                var imageName = fileResult.Item2;
                model.MovieImage = imageName;
            }
            var result = _movieService.Update(model);
            if (result)
            {
                TempData["msg"] = "Added Successfully";
                return RedirectToAction(nameof(MovieList));
            }
            else
            {
                TempData["msg"] = "Error on Server Side";
                return View(model);
            }
        }
        public IActionResult MovieList() 
        {
            var data = this._movieService.List();
            return View(data);
        }
        public IActionResult Delete(int id)
        {
           
            var result = _movieService.Delete(id);
            return RedirectToAction(nameof(MovieList));
            
            
        }

    }
}

BitirmeMovieStore/BitirmeMovieStore/Controllers/UserController.cs
using AutoMapper;
using BitirmeMovieStore.Entities;
using BitirmeMovieStore.Models;
using Microsoft.AspNetCore.Mvc;
using NETCore.Encrypt.Extensions;

namespace BitirmeMovieStore.Controllers
{
    public class UserController : Controller
    {
        private readonly DatabaseContext _databaseContext;
        private readonly IMapper _mapper;
        private readonly IConfiguration _configuration;


        public UserController(DatabaseContext databaseContext, IMapper mapper, IConfiguration configuration)
        {
            _databaseContext = databaseContext;
            _mapper = mapper;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            List<UserModel> users = _databaseContext.Users.ToList().Select(x=> _mapper.Map<UserModel>(x)).ToList();
            return View(users);
        }
        private string DoMD5HashedString(string s)
        {
            string md5Salt = _configuration.GetValue<string>("AppSettings:MD5Salt");
            string salted = s + md5Salt;
            string hashed = salted.MD5();
            return hashed;
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateUserModel model)
        {
            if(ModelState.IsValid)
            {
                //Veritabanında bu kullanıcı adına sahip başka bir kullanıcı var mı?
                if (_databaseContext.Users.Any(x=>x.Username.ToLower()==model.Username.ToLower()))
                {
                    ModelState.AddModelError(nameof(model.Username),"Username is already exists.");
                    return View(model);
                }
                string hashedPassword = DoMD5HashedString(model.Password);
                User user= _mapper.Map<User>(model);
                user.Password = hashedPassword;
                _databaseContext.Users.Add(user);
                _databaseContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        public IActionResult Edit(Guid id)
        {
            User user = _databaseContext.Users.Find(id);
            EditUserModel model = _mapper.Map<EditUserModel>(user);
            return View(model);
        }
        [HttpPost]
        public IActionResult Edit(Guid id, EditUserModel model)
        {
            if (ModelState.IsValid)
            {
                //Kullanıcının kendi haricindeki diğer kullanıcılarla kıyaslama yapılır
                if (_databaseContext.Users.Any(x => x.Username.ToLower() == model.Username.ToLower() && x.Id != id))
                {
                    ModelState.AddModelError(nameof(model.Username), "Username is already exists.");
                    return View(model);
                }
                User user = _databaseContext.Users.Find(id);
                _mapper.Map(model, user);    //Modeldekileri user'a at
                _databaseContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        
        public IActionResult Delete(Guid id)
        {
           
            User user = _databaseContext.Users.Find(id);

            if(user != null)
            {
                _databaseContext.Users.Remove(user);
                _databaseContext.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

BitirmeMovieStore/BitirmeMovieStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BitirmeMovieStore</title>
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/forms.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" href="/images/movie_filter_FILL0_wght400_GRAD0_opsz48.svg">
    <link href="https://fonts.googleapis.com/css2?family=Mukta:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/toastrjs/toastr.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BitirmeMovieStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BitirmeMovieStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        

                        @if(User.Identity.IsAuthenticated)
                        {
                            if(User.IsInRole("admin"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-dark" asp-action="Index" asp-controller="Admin" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Administrator
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a asp-action="Index" asp-controller="User" class="dropdown-item">Users</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-dark" asp-action="Index" asp-controller="Movie" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Movie
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a asp-action="MovieList" asp-controller="Movie" class="dropdown-item">Movies</a></li>
                                        <li><a asp-action="Add" asp-controller="Movie" class="dropdown-item">Add Movie</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-dark" asp-action="Index" asp-controller="Genre" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Genre
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a asp-action="GenreList" asp-controller="Genre" class="dropdown-item">Genres</a></li>
                                        <li><a asp-action="Add" asp-controller="Genre" class="dropdown-item">Add Genre</a></li>
                                    </ul>
                                </li>
                            }
                            
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Profile">
                                    <i class="fa-solid fa-user me-2"></i>@User.FindFirst("Username").Value
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">
                                    <i class="fa-solid fa-right-from-bracket me-2"></i>Logout
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">
                                    <i class="fa-solid fa-right-to-bracket me-2"></i>Login
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">
                                    <i class="fa-solid fa-user me-2"></i>Register
                                </a>
                            </li>
                        }

                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BitirmeMovieStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastrjs/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>